import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';

const html = readFileSync(new URL('../src/views/game.html', import.meta.url), 'utf8');
const css = readFileSync(new URL('../src/style.css', import.meta.url), 'utf8');
const profile = readFileSync(new URL('../src/profileController.js', import.meta.url), 'utf8');
const ratingGraph = readFileSync(new URL('../src/profileRatingGraph.js', import.meta.url), 'utf8');

assert.ok(html.includes('id="btn-open-profile"'));
assert.ok(html.includes('id="modal-profile"'));
assert.ok(html.includes('id="profile-modal-history"'));
assert.ok(html.includes('id="profile-content"'));
assert.ok(!html.includes('class="profile-user-detail"'));
assert.ok(!html.includes('id="btn-edit-status"'));
assert.ok(css.includes('grid-column: 1 / 3;'));
assert.ok(css.includes('grid-row: 1 / 3;'));
assert.ok(html.includes('class="profile-rating-panel"'));
assert.ok(html.includes('class="profile-rating-chart"'));
assert.match(html, /profile-rating-summary[\s\S]*profile-rating-heading[\s\S]*profile-rating-chart/);
assert.ok(!html.includes('레이팅 전적 없음'));
assert.equal((html.match(/<small>전적 없음<\/small>/g) || []).length, 2);
assert.match(css, /\.history-avatar-profile-btn \.history-avatar-mini\s*\{[^}]*display:\s*block;/);
assert.match(css, /#profile-content\s*\{[^}]*flex:\s*1;[^}]*min-height:\s*0;[^}]*height:\s*auto;/);
assert.match(css, /#profile-content > \.history-card\s*\{[^}]*min-height:\s*0;[^}]*max-height:\s*none;/);
assert.match(css, /\.profile-modal-actions\s*\{[^}]*align-self:\s*flex-start;/);
assert.ok(html.includes('id="btn-my-profile"'));
assert.ok(profile.includes("title.textContent = isMine ? '내 프로필' : '유저 프로필'"));
assert.ok(profile.includes("document.getElementById('btn-my-profile')?.classList.toggle('hidden', isMine)"));
assert.match(css, /\.profile-modal-card\s*\{[^}]*overflow:\s*hidden;/);
assert.match(css, /\.profile-modal-history\s*\{[^}]*overflow-y:\s*scroll;[^}]*scrollbar-gutter:\s*stable;/);
assert.match(css, /\.profile-normal-stats\s*\{[^}]*grid-template-columns:\s*repeat\(3,\s*minmax\(0,\s*1fr\)\);/);
assert.doesNotMatch(css, /\.profile-top-augments,\s*\.profile-normal-stats\s*\{[^}]*border-left:/);
assert.match(css, /\.profile-normal-stats > div\s*\{[^}]*height:\s*64px;/);
assert.match(css, /\.profile-rating-chart\s*\{[^}]*width:\s*70%;[^}]*height:\s*83px;/);
assert.match(css, /\.profile-rating-line\s*\{[^}]*stroke-width:\s*3;/);
assert.match(css, /\.profile-rating-line\s*\{[^}]*stroke:\s*#60a5fa;/);
assert.match(css, /\.profile-rating-area\s*\{[^}]*fill:\s*rgba\(59,\s*130,\s*246,\s*0\.3\);/);
assert.match(css, /\.profile-rating-point\s*\{[^}]*border-radius:\s*50%;/);
assert.match(css, /\.profile-rating-point\s*\{[^}]*width:\s*9\.6px;[^}]*height:\s*9\.6px;/);
assert.match(css, /\.profile-rating-point-halo\s*\{[^}]*width:\s*12\.48px;[^}]*height:\s*12\.48px;/);
assert.match(css, /\.profile-rating-chart\.is-rating-point-shrinking \.profile-rating-point-halo\s*\{[^}]*scale\(0\.7692\);/);
assert.equal((html.match(/class="profile-rating-area"/g) || []).length, 2);
assert.equal((html.match(/class="profile-rating-area" d="M0 32H240V64H0Z"/g) || []).length, 2);
assert.equal((html.match(/class="profile-rating-point"/g) || []).length, 2);
assert.equal((html.match(/class="profile-rating-point-halo"/g) || []).length, 2);
assert.equal((html.match(/preserveAspectRatio="none"/g) || []).length, 2);
assert.ok(profile.includes('renderProfileRatingGraph(chart, userData, chart.dataset.ratingMode)'));
assert.ok(ratingGraph.includes('getRatingSeries(userData, mode)'));
assert.match(ratingGraph, /const areaPath = `M0 .*L240 .*V64H0Z`/);
assert.ok(ratingGraph.includes('chart.onpointermove'));
assert.ok(ratingGraph.includes('setTimeout(hidePoint, 1000)'));
assert.ok(ratingGraph.includes("chart.classList.add('is-rating-point-hiding')"));
assert.ok(ratingGraph.includes("position > 0.8 ? '4px'"));
assert.ok(profile.includes('class="profile-top-augment-icon"'));
assert.ok(profile.includes('<span aria-hidden="true">/</span>'));
assert.ok(profile.includes('openProfileModal(button.dataset.profileUid)'));
assert.ok(profile.includes('sessionStorage.getItem(viewKey)'));

console.log('profile layout checks passed');
